---

- name: Dovecot and Plugins are installed via Aptitude
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-mysql
