---

# TODO use custom compile flags
# Dovecot with MySQL support
- name: Install Dovecot and plugins
  pkgng: name={{item}} state=present
  with_items:
    - dovecot2
    - dovecot2-antispam-plugin
    - dovecot-pigeonhole

