---

# Combine Configuration
- set_fact: _dovecot_config="{{ dovecot_default_config | combine(dovecot_config, recursive=True) }}"
  no_log: true
- set_fact: _dovecot_mysql="{{ dovecot_default_mysql | combine(dovecot_mysql, recursive=True) }}"
  no_log: true

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- name: dovecot service is enabled
  service: name=dovecot enabled=yes

- name: vmail group exists
  group:
    name: "{{ _dovecot_config.vmail.group }}"
    system: yes
    state: present

# TODO: Don't we need a home directory? Tilde is used in 90-sieve.conf.j2 
- name: vmail user exists
  user:
    name: "{{ _dovecot_config.vmail.user }}"
    group: "{{ _dovecot_config.vmail.group }}"
    createhome: no
    system: yes
    append: yes
    state: present

# TODO: This should not actually create the directory. More like an assertion. ???
- name: vmail directory exists
  file:
    name: "{{ _dovecot_config.vmail.directory }}"
    state: directory
    owner: "{{ _dovecot_config.vmail.user }}"
    group: "{{ _dovecot_config.vmail.group }}"
    mode: "u=rwx,g=rwx,o="
  notify:
    - restart dovecot

- name: Dovecot configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{_dovecot_config.config_dir}}"
    - "{{_dovecot_config.config_dir}}/managed.conf.d"
  notify:
    - restart dovecot

- name: Dovecot is configured globally
  template:
    src: "{{ item.src }}"
    dest: "{{ _dovecot_config.config_dir }}/{{ item.src | replace('.j2', '') }}"
    mode: "{{ item.mode | default('u=rw,g=r,o=r') }}"
  with_items:
    - src: dovecot.conf.j2
    - src: auth-sql.conf.ext.j2
      mode: "u=rw,g=,o="
    - src: dovecot-quota-warning-template-admin.txt.j2
    - src: dovecot-quota-warning-template-user.txt.j2
  notify:
    - restart dovecot

# TODO: Use the least ugly solution to take care of unmanaged config files in the target directory
# Might involve http://stackoverflow.com/questions/16385507/ansible-delete-unmanaged-files-from-directory 
- name: Dovecot is configured
  template:
    src: "managed.conf.d/{{ item }}.j2"
    dest: "{{ _dovecot_config.managed_config_dir }}/{{ item }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - 10-auth.conf
    - 10-logging.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
    - 15-lda.conf
    - 15-mailboxes.conf
    - 20-imapd.conf
    - 20-lmtpd.conf
    - 20-managesieve.conf
    - 90-antispam.conf
    - 90-quota.conf
    - 90-sieve.conf
  notify:
    - restart dovecot

- name: Sync custom scripts for quota warning
  copy:
    src: dovecot-quota-warning.py
    dest: "{{ _dovecot_config.config_dir }}/dovecot-quota-warning.py"
    mode: "u=rx,g=rx,o=rx"
  notify:
    - restart dovecot

- name: Place quota warning request URL file
  when: quota_notification_url is defined
  copy: 
    content: "{{ quota_notification_url }}"
    dest: "{{ _dovecot_config.config_dir }}/dovecot-quota-warning-request-url"
  notify:
    - restart dovecot

# Antispam bridge  
#- name: 
#    - src: sudoers.d/dovecot-antispam-sa-learn.j2
#      mode: "u=rw,g=,o="
#
#- src: dovecot-antispam-sa-learn.sh
#      mode: "u=rx,g=rx,o=rx"
#      owner: "{{vmail_user}}"
#      group: "{{vmail_group}}"
#
